In [26]:
import numpy as np
class Graph:
    def __init__(self,vertices):
        self.vertices =vertices
        self.adjmat = np.zeros((vertices,vertices))
       
       
    def insert_edge(self,u,v,x=1):
        self.adjmat[u][v] =x
       
    def remove_edge(self,u,v):
        self.adjmat[u][v]=0
       
       
    def vertices(self):
        for i in range(self.vertices):
            print(i, end=" ")
       
    def edges(self):
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.adjmat[i][j]!=0:
                    print(i, "--",j)
               
    def exist_edge(self,u,v):
        return self.adjmat[u][v]!=0
   
    def vertex_count(self):
        return self.vertices
   
    def edge_count(self):
        count=0
        for i in range(self.vertices):
            for j in range(self.vertices):
                if self.adjmat[i][j]!=0:
                    count+=1
        return count
   
   
    def outdegree(self,v):
        count=0
        for j in range(self.vertices):
            if self.adjmat[v][j]!=0:
                count+=1
        return count
   
    def indegree(self,v):
        count=0
        for j in range(self.vertices):
            if self.adjmat[j][v]!=0:
                count+=1
        return count
   
    def display_mat(self):
        return (self.adjmat)

def main():
    try:
        
        G=Graph(4)
        G.insert_edge(0,1)
        G.insert_edge(0,2)
        G.insert_edge(1,0)
        G.insert_edge(1,2)
        G.insert_edge(2,0)
        G.insert_edge(2,1)
        G.insert_edge(2,3)
        G.insert_edge(3,2)
        print("Adjacency Matrix:\n", G.display_mat())

        print("\nNumber of Edges:", G.edge_count())
        print("\nList of edges:")
        G.edges()
        print("\nNumber of vertices:",G.vertex_count())
        print("\nVertex List: " )
        (G.vertices)


        n1 = int(input("\nNode 1: "  ))
        n2 = int(input("Node 2: "))
        print("\nEdge between the given vertex: ", G.exist_edge(n1,n2))
        print("Indegree of", n1, "is", G.indegree(n1))
        print("Indegree of", n2, "is", G.indegree(n2))
        print("Outdegree of", n1, "is", G.outdegree(n1))
        print("Outdegree of", n2, "is", G.outdegree(n2))

    except:
        print("Invalid Value")
    

In [28]:
main()

Adjacency Matrix:
 [[0. 1. 1. 0.]
 [1. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]]

Number of Edges: 8

List of edges:
0 -- 1
0 -- 2
1 -- 0
1 -- 2
2 -- 0
2 -- 1
2 -- 3
3 -- 2

Number of vertices: 4

Vertex List: 

Node 1: p
Invalid Value
